#!/usr/bin/env python3
"""Generate apps/orcsdr-tab5/ui/js8_ldpc_graph.hpp from the specification file docs/js8/spec/js8_ldpc_174_87.json.

The header holds the parity-check graph in the format the generic FEC engine (js8_fec) consumes. Edge numbering is check-major: edge e is the e-th entry
of the concatenated check rows. Reproduce:  python tools/js8-spec/gen_ldpc_graph.py docs/js8/spec/js8_ldpc_174_87.json apps/orcsdr-tab5/ui/js8_ldpc_graph.hpp
"""
import hashlib, json, sys

spec_path, out_path = sys.argv[1], sys.argv[2]
raw = open(spec_path, "rb").read()
spec = json.loads(raw)
rows = spec["check_rows"]
n, m = spec["dimensions"]["n"], spec["dimensions"]["m"]
assert (n, m) == (174, 87) and len(rows) == m
assert all(rows[i][0] == i and rows[i] == sorted(rows[i]) and all(0 <= v < n for v in rows[i]) for i in range(m))
check_offsets, check_vars = [0], []
edges_of = [[] for _ in range(n)]
for r in rows:
    for v in r:
        edges_of[v].append(len(check_vars))
        check_vars.append(v)
    check_offsets.append(len(check_vars))
var_offsets, var_edges = [0], []
for v in range(n):
    var_edges.extend(edges_of[v])
    var_offsets.append(len(var_edges))

def array(name, ctype, values, per_line=16):
    lines = ["inline constexpr %s %s[] = {" % (ctype, name)]
    for i in range(0, len(values), per_line):
        lines.append("    " + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)

text = """// GENERATED by tools/js8-spec/gen_ldpc_graph.py from docs/js8/spec/js8_ldpc_174_87.json (SHA-256 %s). Do not edit.
// JS8 LDPC(174,87) parity-check graph: 87 checks over 174 variables, %d edges. Codeword order: 87 parity bits first, then 87 information bits.
// Provenance of the underlying facts is recorded in the specification file (JS8Call JS8.cpp, GPL-SOURCE, blob b19aa96c...); only the numbers are used here.
#pragma once

#include <cstddef>
#include <cstdint>

namespace orcsdr::js8::ldpc_graph {

inline constexpr size_t kVariables = 174;
inline constexpr size_t kChecks = 87;
inline constexpr size_t kInfoBits = 87;
inline constexpr size_t kEdges = %d;

%s

%s

%s

%s

}  // namespace orcsdr::js8::ldpc_graph
""" % (hashlib.sha256(raw).hexdigest(), len(check_vars), len(check_vars),
       array("kCheckOffsets", "uint16_t", check_offsets), array("kCheckVariables", "uint16_t", check_vars),
       array("kVariableOffsets", "uint16_t", var_offsets), array("kVariableEdges", "uint16_t", var_edges))
open(out_path, "w", newline="\n").write(text)
print("wrote", out_path, "edges", len(check_vars))
