#include "../apps/orcsdr-tab5/ui/ft8_codec.hpp"

#include <array>
#include <cassert>
#include <cstdint>
#include <cstring>

namespace {

using namespace orcsdr::ft8::codec;

PayloadBits payload_from_text(const char* text) {
  assert(text != nullptr);
  assert(std::strlen(text) == kPayloadBits);
  PayloadBits bits{};
  for (std::size_t i = 0; i < kPayloadBits; ++i) {
    assert(text[i] == '0' || text[i] == '1');
    bits[i] = static_cast<uint8_t>(text[i] - '0');
  }
  return bits;
}

void test_crc_public_domain_vector() {
  // Input example is from the authors' public-domain gen_crc14.f90 helper in
  // ft4_ft8_protocols.tgz. Reference helper output: 01010101111001 = 5497.
  const auto payload = payload_from_text(
      "00000000000000000000000000100000010011011111110011011100100010100001010000001");
  assert(crc14(payload) == 5497u);
  auto message = append_crc(payload);
  assert(crc_valid(message));
  message[20] ^= 1u;
  assert(!crc_valid(message));
}

void test_standard_callsign_public_domain_vectors() {
  uint32_t value = 0;
  // Values generated by the authors' public-domain std_call_to_c28.f90.
  assert(encode_standard_callsign("K1ABC", &value));
  assert(value == 10214965u);
  assert(encode_standard_callsign("W9XYZ", &value));
  assert(value == 12751800u);
  assert(encode_standard_callsign("k1abc", &value));
  assert(value == 10214965u);
  assert(encode_standard_callsign("K1A", &value));
  assert(value == 10214908u);
  assert(encode_standard_callsign("KA1A", &value));
  assert(value == 157050088u);
  assert(!encode_standard_callsign("PJ4/K1ABC", &value));
  assert(!encode_standard_callsign("NO-DIGIT", &value));
  // The digit position is fixed by the packing layout, so a prefix may contain a digit (real calls such as A92EE).
  assert(encode_standard_callsign("A92EE", &value));
  assert(encode_standard_callsign("K12ABC", &value));
  assert(!encode_standard_callsign("AEEE", &value));      // no digit in position 2 or 3
  assert(!encode_standard_callsign("AB123", &value));     // suffix must be letters
  assert(!encode_standard_callsign("11ABC", &value));
  assert(!encode_standard_callsign("", &value));
  assert(!encode_standard_callsign("K1ABC", nullptr));
}

void test_hash_public_domain_vectors() {
  CallsignHashes hashes{};
  // Values generated by the authors' public-domain hashcodes.f90.
  assert(callsign_hashes("PJ4/K1ABC", &hashes));
  assert(hashes.h10 == 346u);
  assert(hashes.h12 == 1387u);
  assert(hashes.h22 == 1420834u);
  assert(callsign_hashes("K1ABC", &hashes));
  assert(hashes.h10 == 712u);
  assert(hashes.h12 == 2851u);
  assert(hashes.h22 == 2920267u);
  assert(callsign_hashes("k1abc", &hashes));
  assert(hashes.h22 == 2920267u);
  assert(!callsign_hashes("BAD@CALL", &hashes));
  assert(!callsign_hashes("ABCDEFGHIJKL", &hashes));
  assert(!callsign_hashes("K1ABC", nullptr));
}

void test_gray_mapping() {
  // QEX Table 3, indexed by input bits 000..111.
  constexpr std::array<uint8_t, 8> expected{{0, 1, 3, 2, 5, 6, 4, 7}};
  for (uint8_t value = 0; value < 8; ++value) {
    const uint8_t b0 = static_cast<uint8_t>((value >> 2u) & 1u);
    const uint8_t b1 = static_cast<uint8_t>((value >> 1u) & 1u);
    const uint8_t b2 = static_cast<uint8_t>(value & 1u);
    assert(gray_tone(b0, b1, b2) == expected[value]);
  }
}

void test_channel_framing() {
  DataTones data{};
  for (std::size_t i = 0; i < data.size(); ++i)
    data[i] = static_cast<uint8_t>(i & 7u);
  const ChannelTones frame = frame_data_tones(data);
  constexpr std::array<uint8_t, 7> costas{{3, 1, 4, 0, 6, 5, 2}};
  for (std::size_t i = 0; i < costas.size(); ++i) {
    assert(frame[i] == costas[i]);
    assert(frame[36 + i] == costas[i]);
    assert(frame[72 + i] == costas[i]);
  }
  for (std::size_t i = 0; i < 29; ++i) {
    assert(frame[7 + i] == data[i]);
    assert(frame[43 + i] == data[29 + i]);
  }
}

void test_codeword_mapping() {
  CodewordBits codeword{};
  for (std::size_t i = 0; i < codeword.size(); ++i)
    codeword[i] = static_cast<uint8_t>((i * 5u + 1u) & 1u);
  DataTones tones{};
  assert(codeword_to_data_tones(codeword, &tones));
  for (std::size_t i = 0; i < tones.size(); ++i) {
    const std::size_t bit = i * 3;
    assert(tones[i] == gray_tone(codeword[bit], codeword[bit + 1], codeword[bit + 2]));
    assert(tones[i] < 8u);
  }
  assert(!codeword_to_data_tones(codeword, nullptr));
}

}  // namespace

int main() {
  assert(orcsdr::ft8::codec::self_check());
  test_crc_public_domain_vector();
  test_standard_callsign_public_domain_vectors();
  test_hash_public_domain_vectors();
  test_gray_mapping();
  test_channel_framing();
  test_codeword_mapping();
  return 0;
}
