[platformio]
src_dir = ui

[env:m5tab5_ui]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1
framework = arduino
platform_packages =
    framework-arduinoespressif32@https://github.com/espressif/arduino-esp32/releases/download/3.3.8/esp32-core-3.3.8.tar.xz
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
upload_speed = 1500000
monitor_speed = 115200
extra_scripts = pre:tools/patch_m5gfx.py
lib_extra_dirs =
    ../../components
lib_deps =
    m5stack/M5Unified @ 0.2.15
    m5stack/M5GFX @ 0.2.21
    rtl_sdr_v4_esp
build_flags =
    -DARDUINO_M5STACK_TAB5=1
    -DBOARD_HAS_PSRAM=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=4
    -DRTL_USE_LEGACY_USB=0
    -I../../components/rtl_sdr_v4_esp/include
    -I../../components/rtl_sdr_v4_esp/private

[env:m5tab5_lora_test]
extends = env:m5tab5_ui
build_flags =
    ${env:m5tab5_ui.build_flags}
    -DORC_LORA_TEST_BUILD=1
