#!/usr/bin/env python3
"""Generate apps/orcsdr-tab5/ui/ft8_world_data.cpp: a coarse offline world outline for the FT8 MAP tab.

Source: Natural Earth 1:110m land and country boundary lines (public domain), read from a local checkout:
  python tools/gen_ft8_world.py <natural-earth-5.1.2-dir> <output.cpp>
Points are stored as 0.01 degree int16 pairs. Reproducible: same input, same output.
"""
import sys
import geopandas as gpd
from shapely.geometry import LineString, MultiLineString, Polygon, MultiPolygon

root, out = sys.argv[1], sys.argv[2]
TOL = 0.3  # degrees; keeps coastlines recognisable at the fitted/world zoom without bloating flash


def lines_of(geom):
    if isinstance(geom, (Polygon, MultiPolygon)):
        polys = [geom] if isinstance(geom, Polygon) else list(geom.geoms)
        for p in polys:
            yield list(p.exterior.coords)
    elif isinstance(geom, LineString):
        yield list(geom.coords)
    elif isinstance(geom, MultiLineString):
        for g in geom.geoms:
            yield list(g.coords)


segments = []  # (kind, [(lon, lat)...])
for kind, name in ((0, "ne_110m_land"), (1, "ne_110m_admin_0_boundary_lines_land")):
    df = gpd.read_file("%s/110m/datasets/%s/%s.shp" % (root, name, name))
    for geom in df.geometry:
        if geom is None:
            continue
        g = geom.simplify(TOL, preserve_topology=False)
        for pts in lines_of(g):
            if len(pts) >= 2:
                segments.append((kind, pts))

pts_flat, segs = [], []
for kind, pts in segments:
    segs.append((len(pts_flat) // 2, len(pts), kind))
    for lon, lat in pts:
        pts_flat += [int(round(lon * 100)), int(round(lat * 100))]

with open(out, "w", newline="\n") as f:
    f.write("// Generated by tools/gen_ft8_world.py from Natural Earth 1:110m (public domain). Do not edit.\n")
    f.write('#include "ft8_world_data.hpp"\n\nnamespace orcsdr::ft8 {\n\n')
    f.write("const int16_t kWorldPoints[] = {\n")
    for i in range(0, len(pts_flat), 16):
        f.write("    " + ",".join(str(v) for v in pts_flat[i:i + 16]) + ",\n")
    f.write("};\nconst size_t kWorldPointCount = %d;\n\n" % (len(pts_flat) // 2))
    f.write("const WorldSegment kWorldSegments[] = {\n")
    for start, count, kind in segs:
        f.write("    {%d, %d, %d},\n" % (start, count, kind))
    f.write("};\nconst size_t kWorldSegmentCount = %d;\n\n}  // namespace orcsdr::ft8\n" % len(segs))
print("segments", len(segs), "points", len(pts_flat) // 2, "bytes ~", len(pts_flat) * 2)
