#pragma once

#include <cstddef>
#include <cstdint>

namespace orcsdr::ft8 {

// Coarse offline world outline for the MAP tab (generated by tools/gen_ft8_world.py from Natural Earth, public domain).
// Points are longitude, latitude in 0.01 degree units; a segment is a polyline of `count` points starting at `start`.
struct WorldSegment {
  uint16_t start;
  uint16_t count;
  uint8_t kind;   // 0 = coastline/land outline, 1 = country border
};

extern const int16_t kWorldPoints[];
extern const size_t kWorldPointCount;
extern const WorldSegment kWorldSegments[];
extern const size_t kWorldSegmentCount;

}  // namespace orcsdr::ft8
